### PR TITLE
Upgrade standard to the latest version

### PR DESCRIPTION
**Pull request by travi**

### CODE REVIEW

**Comment by travi** [comment]
@jwsloan it looks like your approval still isnt privileged enough to let me merge. did you end up accepting the invitation?

**Comment by jwsloan** [comment]
I noticed that, @travi . I thought I had, but apparently not. Maybe @gr2m would invite me again.

**Comment by travi** [comment]
assuming that it is still out there, i think you should be able to go to https://github.com/probot/settings/invitations

**Comment by gr2m** [comment]
Should be fixed now! @jwsloan had the Triage permission, I've set it to Write now

**Comment by travi** [comment]
thanks @gr2m

**Pull request merged**
