### PR TITLE
test(integration): split the push test into plugin tests

### PR DESCRIPTION
**Pull request by travi**
for #145

### CODE REVIEW

**Comment by travi** [comment]
as i've added more tests, i've outgrown things being focused on the push event. i'm hoping splitting this way will also make it easier to support additional events that trigger processing

**Comment by travi** [comment]
any idea what is going on with travis for this project @gr2m? looks like its disabled or something: https://travis-ci.com/probot/settings

**Comment by gr2m** [comment]
Hmm I dunno, but maybe let's take the opportunity and migrate tests to actions?

**Comment by travi** [comment]
Yeah, that seems reasonable. Since I don't have visibility to the deployment details, is there anything we need to coordinate there? I think it at least waits for Travis to pass before deploying currently.

**Comment by gr2m** [comment]
> I think it at least waits for Travis to pass before deploying currently

I don't mind it deploying without waiting for tests, as long as we enforce the pull request review process.

**Comment by travi** [comment]
i suppose thats true. since i normally follow trunk-based development, i tend to be a bit more protective of mainline verification

**Pull request merged**
