### PR TITLE
Improve readability of key readme sections

### PR DESCRIPTION
**Pull request by travi**
also, i don't seem to be able to add @jwsloan as a reviewer. are additional permissions needed for that?

-----
[View rendered README.md](https://github.com/travi/settings/blob/readme-sections/README.md)

### CODE REVIEW

**Comment by gr2m** [comment]
I invited @jwsloan

**Comment by travi** [comment]
@jwsloan mind adding an approving review? :)

**Comment by travi** [comment]
well, it looks like you did, but it didnt unblock the merge. @gr2m think that would be because you added after the PR was opened?

**Comment by gr2m** [comment]
Let's see if it works next time :)

**Comment by gr2m** [comment]
@jwsloan you still need to accept my invitation: https://github.com/probot/settings/invitations

**Pull request merged**
