### PR TITLE
Introduce esbuild so we have a CommonJS export

### PR DESCRIPTION
**Pull request by mattwynne**
It turns out that #569 left people unable to load the app, since Probot seems to assume your code is CommonJS.

This is one possible fix. I would prefer if if there's a way we can figure out to have Probot be happy to load our ESM code directly, but I can't see it yet.

### CODE REVIEW

**Comment by mattwynne** [comment]
Ref: https://github.com/probot/probot/issues/1684 and https://github.com/probot/probot/pull/1685

**Comment by nitrocode** [comment]
Thanks @mattwynne for submitting this follow up PR.

@travi can we get another review on this ? Currently probot/settings is broken for us unless we use a self-hosted version of an earlier commit.

**Comment by nitrocode** [comment]
Could we also look into this version ? It seems like v12 is incorrect. This app must be using at least v16.

https://github.com/probot/settings/blob/master/.nvmrc

**Comment by travi** [comment]
sorry for the delayed response here. i'm glad that you currently have the ability to work around this by hosting at an earlier commit until we get this resolved.

i'm not sure that the additional complexity is worth it to build the app back to cjs after moving the source to esm. i think i lean more in the direction of reverting the esm change until probot is ready to support it. as much as i like moving forward in this direction, i think it would be better to defer the complexity for now. what are your thoughts around that approach @mattwynne?

**Comment by travi** [comment]
> Could we also look into this version ? It seems like v12 is incorrect. This app must be using at least v16.

thanks for highlighting that. we should definitely update that to v16 at this point. i normally use https://github.com/actions/setup-node/blob/ea3459bb459f783f186dcfc5229793d2c6f40b25/docs/advanced-usage.md#node-version-file at https://github.com/probot/settings/blob/dd947f598604640190b68d75e998fff1bdff4f27/.github/workflows/node-ci.yml#L19 along with the `.nvmrc`, but overlooked that in this project. would you be interested in contributing a PR with those two changes for us @nitrocode?

**Comment by nitrocode** [comment]
To get this in a working state again, I think we should revert the last PR commit https://github.com/probot/settings/commit/9fb82c442188bd3df5524ac8b83f3aad3775b91b unless we can know this PR will resolve the current issue. Tests are failing in this PR.

With regard to v16 nvmrc, I put in the tiny PR https://github.com/probot/settings/pull/586 :)

**Comment by nitrocode** [comment]
We may want to expand on the current test suite to also run the current build to ensure it will start up. That would help future PRs too.

**Comment by mattwynne** [comment]
> sorry for the delayed response here. i'm glad that you currently have the ability to work around this by hosting at an earlier commit until we get this resolved.
> 
> i'm not sure that the additional complexity is worth it to build the app back to cjs after moving the source to esm. i think i lean more in the direction of reverting the esm change until probot is ready to support it. as much as i like moving forward in this direction, i think it would be better to defer the complexity for now. what are your thoughts around that approach @mattwynne? we would obviously still have the esm version available in history so we could bring it back once it is better supported.

Honestly, my preference would be to move the codebase to Typescript and then we can compile it down to whatever form of Javascript we like 😁 but I realise that's probably a separate discussion :trollface: 

I'm not married to these changes but I think we should accept that the old commit will be pretty useless once the codebase has moved on. It only took a few hours though so we could easily do it again.

I'm easy either way.

**Comment by nitrocode** [comment]
Ok, I put in PR https://github.com/probot/settings/pull/587 to revert PR #569

**Comment by travi** [comment]
sorry. i did indent to get this taken care of over the weekend, so thanks for the nudge @nitrocode

**Comment by travi** [comment]
closing this PR since we reverted the ESM change. thanks for digging into the ESM change and this workaround. i hope it will make sense to resurrect some of the pieces soon if probot ends up supporting things better.

**Comment by mattwynne** [comment]
> We may want to expand on the current test suite to also run the current build to ensure it will start up. That would help future PRs too.

I think that would be really helpful

**Comment by travi** [comment]
i agree that it would be ideal if we could find a way to verify that automatically. i'm hopeful that once we switch over to vercel for hosting that the preview builds for PRs can help with this.

**Pull request closed without merging**
